<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Language;
use App\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::where('id', '!=', NULL)->update(['language_id' => NULL]);
        DB::table('languages')->where('id', '!=', 0)->delete();
        DB::table('countries')->where('id', '!=', 0)->delete();
        $data = [
            ['name' => 'Afghanistan', 'code' => 'af', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Åland Islands', 'code' => 'ax', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Albania', 'code' => 'al', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Algeria', 'code' => 'dz', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'American Samoa', 'code' => 'as', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Andorra', 'code' => 'ad', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angola', 'code' => 'ao', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Anguilla', 'code' => 'ai', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Antarctica', 'code' => 'aq', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Antigua and Barbuda', 'code' => 'ag', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Argentina', 'code' => 'ar', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Armenia', 'code' => 'am', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Aruba', 'code' => 'aw', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Australia', 'code' => 'au', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Austria', 'code' => 'at', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Azerbaijan', 'code' => 'az', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bahamas', 'code' => 'bs', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bahrain', 'code' => 'bh', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh', 'code' => 'bd', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Barbados', 'code' => 'bb', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Belarus', 'code' => 'by', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Belgium', 'code' => 'be', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Belize', 'code' => 'bz', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Benin', 'code' => 'bj', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bermuda', 'code' => 'bm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bhutan', 'code' => 'bt', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bolivia (Plurinational State of)', 'code' => 'bo', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'bq', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'ba', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Botswana', 'code' => 'bw', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bouvet Island', 'code' => 'bv', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brazil', 'code' => 'br', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'British Indian Ocean Territory', 'code' => 'io', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brunei Darussalam', 'code' => 'bn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bulgaria', 'code' => 'bg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Burkina Faso', 'code' => 'bf', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Burundi', 'code' => 'bi', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cabo Verde', 'code' => 'cv', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cambodia', 'code' => 'kh', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cameroon', 'code' => 'cm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Canada', 'code' => 'ca', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cayman Islands', 'code' => 'ky', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Central African Republic', 'code' => 'cf', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chad', 'code' => 'td', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chile', 'code' => 'cl', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'China', 'code' => 'cn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Christmas Island', 'code' => 'cx', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'cc', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Colombia', 'code' => 'co', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comoros', 'code' => 'km', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Congo', 'code' => 'cg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Congo, Democratic Republic of the', 'code' => 'cd', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cook Islands', 'code' => 'ck', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Costa Rica', 'code' => 'cr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Côte dIvoire', 'code' => 'ci', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Croatia', 'code' => 'hr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cuba', 'code' => 'cu', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Curaçao', 'code' => 'cw', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cyprus', 'code' => 'cy', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Czechia', 'code' => 'cz', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Denmark', 'code' => 'dk', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Djibouti', 'code' => 'dj', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dominica', 'code' => 'dm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dominican Republic', 'code' => 'do', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ecuador', 'code' => 'ec', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Egypt', 'code' => 'eg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'El Salvador', 'code' => 'sv', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Equatorial Guinea', 'code' => 'gq', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eritrea', 'code' => 'er', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Estonia', 'code' => 'ee', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eswatini', 'code' => 'sz', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ethiopia', 'code' => 'et', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'fk', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Faroe Islands', 'code' => 'fo', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fiji', 'code' => 'fj', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Finland', 'code' => 'fi', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'France', 'code' => 'fr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'French Guiana', 'code' => 'gf', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'French Polynesia', 'code' => 'pf', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'French Southern Territories', 'code' => 'tf', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gabon', 'code' => 'ga', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gambia', 'code' => 'gm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Georgia', 'code' => 'ge', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Germany', 'code' => 'de', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ghana', 'code' => 'gh', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gibraltar', 'code' => 'gi', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Greece', 'code' => 'gr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Greenland', 'code' => 'gl', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Grenada', 'code' => 'gd', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guadeloupe', 'code' => 'gp', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guam', 'code' => 'gu', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guatemala', 'code' => 'gt', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guernsey', 'code' => 'gg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guinea', 'code' => 'gn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guinea-Bissau', 'code' => 'gw', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guyana', 'code' => 'gy', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Haiti', 'code' => 'ht', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'hm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Holy See', 'code' => 'va', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Honduras', 'code' => 'hn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hong Kong', 'code' => 'hk', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hungary', 'code' => 'hu', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Iceland', 'code' => 'is', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'India', 'code' => 'in', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Indonesia', 'code' => 'id', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Iran (Islamic Republic of)', 'code' => 'ir', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Iraq', 'code' => 'iq', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ireland', 'code' => 'ie', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Isle of Man', 'code' => 'im', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Israel', 'code' => 'il', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Italy', 'code' => 'it', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jamaica', 'code' => 'jm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Japan', 'code' => 'jp', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jersey', 'code' => 'je', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jordan', 'code' => 'jo', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kazakhstan', 'code' => 'kz', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kenya', 'code' => 'ke', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiribati', 'code' => 'ki', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Korea (Democratic Peoples Republic of)', 'code' => 'kp', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Korea, Republic of', 'code' => 'kr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kuwait', 'code' => 'kw', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kyrgyzstan', 'code' => 'kg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lao Peoples Democratic Republic', 'code' => 'la', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Latvia', 'code' => 'lv', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lebanon', 'code' => 'lb', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lesotho', 'code' => 'ls', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Liberia', 'code' => 'lr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Libya', 'code' => 'ly', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Liechtenstein', 'code' => 'li', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lithuania', 'code' => 'lt', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Luxembourg', 'code' => 'lu', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Macao', 'code' => 'mo', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Madagascar', 'code' => 'mg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malawi', 'code' => 'mw', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malaysia', 'code' => 'my', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Maldives', 'code' => 'mv', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mali', 'code' => 'ml', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malta', 'code' => 'mt', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Marshall Islands', 'code' => 'mh', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Martinique', 'code' => 'mq', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mauritania', 'code' => 'mr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mauritius', 'code' => 'mu', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mayotte', 'code' => 'yt', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mexico', 'code' => 'mx', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Micronesia (Federated States of)', 'code' => 'fm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Moldova, Republic of', 'code' => 'md', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Monaco', 'code' => 'mc', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mongolia', 'code' => 'mn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Montenegro', 'code' => 'me', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Montserrat', 'code' => 'ms', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Morocco', 'code' => 'ma', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mozambique', 'code' => 'mz', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Myanmar', 'code' => 'mm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Namibia', 'code' => 'na', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nauru', 'code' => 'nr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nepal', 'code' => 'np', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Netherlands', 'code' => 'nl', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'New Caledonia', 'code' => 'nc', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'New Zealand', 'code' => 'nz', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nicaragua', 'code' => 'ni', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Niger', 'code' => 'ne', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nigeria', 'code' => 'ng', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Niue', 'code' => 'nu', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Norfolk Island', 'code' => 'nf', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'North Macedonia', 'code' => 'mk', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Northern Mariana Islands', 'code' => 'mp', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Norway', 'code' => 'no', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Oman', 'code' => 'om', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pakistan', 'code' => 'pk', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Palau', 'code' => 'pw', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Palestine, State of', 'code' => 'ps', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Panama', 'code' => 'pa', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Papua New Guinea', 'code' => 'pg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Paraguay', 'code' => 'py', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Peru', 'code' => 'pe', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Philippines', 'code' => 'ph', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pitcairn', 'code' => 'pn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Poland', 'code' => 'pl', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Portugal', 'code' => 'pt', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Puerto Rico', 'code' => 'pr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Qatar', 'code' => 'qa', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Réunion', 'code' => 're', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Romania', 'code' => 'ro', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Russian Federation', 'code' => 'ru', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rwanda', 'code' => 'rw', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saint Barthélemy', 'code' => 'bl', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'sh', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'kn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saint Lucia', 'code' => 'lc', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saint Martin (French part)', 'code' => 'mf', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'pm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'vc', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Samoa', 'code' => 'ws', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'San Marino', 'code' => 'sm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sao Tome and Principe', 'code' => 'st', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saudi Arabia', 'code' => 'sa', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Senegal', 'code' => 'sn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Serbia', 'code' => 'rs', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Seychelles', 'code' => 'sc', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sierra Leone', 'code' => 'sl', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Singapore', 'code' => 'sg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'sx', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Slovakia', 'code' => 'sk', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Slovenia', 'code' => 'si', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Solomon Islands', 'code' => 'sb', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Somalia', 'code' => 'so', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'South Africa', 'code' => 'za', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'gs', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'South Sudan', 'code' => 'ss', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Spain', 'code' => 'es', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sri Lanka', 'code' => 'lk', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sudan', 'code' => 'sd', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Suriname', 'code' => 'sr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'sj', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sweden', 'code' => 'se', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Switzerland', 'code' => 'ch', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Syrian Arab Republic', 'code' => 'sy', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Taiwan, Province of China', 'code' => 'tw', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tajikistan', 'code' => 'tj', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tanzania, United Republic of', 'code' => 'tz', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thailand', 'code' => 'th', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Timor-Leste', 'code' => 'tl', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Togo', 'code' => 'tg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tokelau', 'code' => 'tk', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tonga', 'code' => 'to', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trinidad and Tobago', 'code' => 'tt', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tunisia', 'code' => 'tn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turkey', 'code' => 'tr', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turkmenistan', 'code' => 'tm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turks and Caicos Islands', 'code' => 'tc', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuvalu', 'code' => 'tv', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uganda', 'code' => 'ug', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ukraine', 'code' => 'ua', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'United Arab Emirates', 'code' => 'ae', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'United Kingdom of Great Britain and Northern Ireland', 'code' => 'gb', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'United States of America', 'code' => 'us', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'um', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uruguay', 'code' => 'uy', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uzbekistan', 'code' => 'uz', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vanuatu', 'code' => 'vu', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Venezuela (Bolivarian Republic of)', 'code' => 've', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Viet Nam', 'code' => 'vn', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Virgin Islands (British)', 'code' => 'vg', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Virgin Islands (U.S.)', 'code' => 'vi', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wallis and Futuna', 'code' => 'wf', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Western Sahara', 'code' => 'eh', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yemen', 'code' => 'ye', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zambia', 'code' => 'zm', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zimbabwe', 'code' => 'zw', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
        ];

        Country::insert($data);
        
        $language =  Language::updateOrCreate(['code' => 'master'], ['name' => 'Master', 'code' => 'master', 'country_id' => Country::where('code', 'us')->first()->id, 'status' => 2]);
        User::whereNull('language_id')->update(['language_id' => $language->id]);
    }
}
